services:
  # Rails Backend
  - type: web
    name: my-api
    plan: free
    runtime: ruby
    buildCommand: cd my_api && bash bin/render-build.sh
    startCommand: cd my_api && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: 6cbaaf2f7e7a8673dd93a3052de119eb

  # Vue.js Frontend
  - type: web
    name: my-frontend
    runtime: static
    buildCommand: |
      cd my_frontend && \
      VUE_APP_GRAPHQL_HTTP="https://my-api.onrender.com/graphql" \
      yarn install && \
      yarn build
    staticPublishPath: my_frontend/dist

databases:
  - name: my-api-db
    plan: free