services:
  - type: web
    name: my-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false  # Set this in the Render Dashboard
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2

  - type: web
    name: my-frontend
    runtime: static
    plan: free
    buildCommand: |
      cd my_frontend
      yarn install
      yarn build
    staticPublishPath: my_frontend/dist
    envVars:
      - key: VUE_APP_GRAPHQL_HTTP
        value: https://my-api.onrender.com/graphql

databases:
  - name: my-api-db
    plan: free
