services:
  - type: web
    name: my-api
    rootDir: my_api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2

  - type: web
    name: my-frontend
    runtime: static
    buildCommand: |
      cd my_frontend
      yarn install
      yarn build
    staticPublishPath: my_frontend/dist
    envVars:
      # Dynamically pulls your API's external URL at build time
      - key: VUE_APP_GRAPHQL_HTTP
        fromService:
          type: web
          name: my-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: my-api-db
    plan: free
