services:
  - type: web
    name: my-api
    plan: free
    runtime: ruby
    buildCommand: cd my_api && bash bin/render-build.sh
    startCommand: cd my_api && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production

  - type: web
    name: my-frontend
    plan: free
    runtime: static
    buildCommand: cd my_frontend && yarn && yarn build
    staticPublishPath: my_frontend/dist
    envVars:
      - key: VUE_APP_GRAPHQL_HTTP
        value: https://my-api.onrender.com/graphql

databases:
  - name: my-api-db
    plan: free
