services:
  - type: web
    name: my-api
    plan: free
    runtime: ruby
    buildCommand: cd my_api && bash bin/render-build.sh
    startCommand: cd my_api && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: ${my-api-db.DATABASE_URL}
      - key: RAILS_MASTER_KEY
        value: your_rails_master_key_here # Replace with your actual key!

  - type: web          # <── Keep as "web" but specify `runtime: static`
    name: my-frontend
    plan: free
    runtime: static    # <── This defines it as a static site
    buildCommand: cd my_frontend && yarn install && yarn build
    staticPublishPath: my_frontend/dist
    envVars:
      - key: VUE_APP_GRAPHQL_HTTP
        value: ${my-api.RENDER_EXTERNAL_URL}/graphql

databases:
  - name: my-api-db
    plan: free