services:
  - type: web
    name: my-api
    plan: free
    runtime: ruby
    buildCommand: cd my_api && bash bin/render-build.sh
    startCommand: cd my_api && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: ${my-api-db.DATABASE_URL} # Link to PostgreSQL database
      - key: RAILS_MASTER_KEY
        value: your_rails_master_key_here # From config/master.key

  - type: web
    name: my-frontend
    plan: free
    runtime: static
    buildCommand: cd my_frontend && yarn install && yarn build
    staticPublishPath: my_frontend/dist
    envVars:
      - key: VUE_APP_GRAPHQL_HTTP
        value: ${my-api.RENDER_EXTERNAL_URL}/graphql # Dynamic backend URL

databases:
  - name: my-api-db
    plan: free
    databaseName: my_api_production
    user: my_api_user